### ISSUE TITLE
Start game.bat not work after update... can you fix? thanks

### ISSUE THREAD

**Issue by Belgharat11091986** [conan513/SPP-AionGermany#2]
=============================[  ### DataBase ###  ]=============================

08:27:28.538 INFO [main]: - Successfully connected to database
08:27:28.570 ERROR[main]: - Critical Error - Thread: main terminated abnormaly: java.lang.Error: Root directory not exists or is not a directory
java.lang.Error: Root directory not exists or is not a directory
        at com.aionemu.commons.database.dao.DAOManager.init(DAOManager.java:75) ~[al-commons.jar:na]
        at com.aionemu.gameserver.GameServer.initUtilityServicesAndConfig(GameServer.java:516) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(GameServer.java:240) ~[AL-Game.jar:na]
Caused by: java.lang.IllegalArgumentException: Root directory not exists or is not a directory
        at com.aionemu.commons.scripting.impl.ScriptContextImpl.<init>(ScriptContextImpl.java:116) ~[al-commons.jar:na]
        at com.aionemu.commons.scripting.impl.ScriptContextImpl.<init>(ScriptContextImpl.java:95) ~[al-commons.jar:na]
        at com.aionemu.commons.scripting.ScriptContextFactory.getScriptContext(ScriptContextFactory.java:47) ~[al-commons.jar:na]
        at com.aionemu.commons.scripting.scriptmanager.ScriptManager.createContext(ScriptManager.java:167) ~[al-commons.jar:na]
        at com.aionemu.commons.scripting.scriptmanager.ScriptManager.load(ScriptManager.java:94) ~[al-commons.jar:na]
        at com.aionemu.commons.database.dao.DAOManager.init(DAOManager.java:72) ~[al-commons.jar:na]
        ... 2 common frames omitted

**Comment by boubouexpress** [comment]
hi did you solve your problem i have exactly the same
